name: flutter_bus_roades
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  bloc: ^8.1.4
  collection: ^1.18.0
  cupertino_icons: ^1.0.2

  dio: ^5.4.1
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.4
  flutter_native_splash: ^2.3.11
  flutter_screenutil: ^5.9.0
  fluttertoast: ^8.2.4
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  intl: ^0.19.0
  json_annotation: ^4.8.1
  logging: ^1.2.0
  meta: ^1.10.0
  path: ^1.8.3
  provider: ^6.1.2
  url_launcher: ^6.2.5

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
